driver:
  name: ec2
  instance_type: t2.micro
  region: eu-west-1
  aws_ssh_key_id: amencke
  security_group_ids: ["sg-7ddbe619"]

transport:
  ssh_key: ~/.ssh/amencke

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[minitest-handler]
      - recipe[my_cookbook_test]
    attributes: { my_cookbook: { greeting: 'Ohai, Minitest!'} }
